# Generated by Django 4.1.1 on 2022-10-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('sub1', models.FloatField()),
                ('sub2', models.FloatField()),
                ('sub3', models.FloatField()),
                ('total', models.FloatField()),
                ('avg', models.FloatField()),
            ],
        ),
    ]
