# Generated by Django 4.1.1 on 2022-10-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBModelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compid', models.IntegerField()),
                ('compname', models.CharField(max_length=30)),
                ('compemp', models.IntegerField()),
                ('compaddr', models.TextField()),
                ('compshrval', models.FloatField()),
            ],
        ),
    ]
